title: Nam Doan # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data-driven story-teller who would like to apply data analytic,
  data visualization, and Machine Learning to build predictive model and
  to solve business problem.
  <br><br>
  <a href="https://www.linkedin.com/in/nam-doan-088084109/">Linkedin</a>   <a href="https://public.tableau.com/profile/nam.h.doan#!//">Tableau</a>
  <br><br>
  <a href="https://github.com/namdoan194/">Github</a>   <a href="https://tinyurl.com/cb9amt8b/">Resume</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
